### ISSUE TITLE
Mako Power Cables

### ISSUE THREAD

**Issue by sisaha9** [Triton-AI/evGoKart-electrical-system#12]
![MakoPinDetails](https://user-images.githubusercontent.com/49205122/163918655-b8628d66-58ef-45ce-9362-a01363077e13.png)

Here are the Mako Pin Details for the CAMERA SIDE pinout. We need about 6 of these to be made

**Comment by jmsanjua** [comment]
As I was making the cable I noticed that it was male. When I checked the camera I saw that it was also male. We need to buy the female version of the cable or get some sort of female/female connector

**Comment by jmsanjua** [comment]
The Power Cables for the Mako cameras just came in. Added a Male XT30 to all of them. They should be connected to the 12V PDN-A power distribution board in the front of the car when it is installed.
![image](https://user-images.githubusercontent.com/81659626/166393247-86ae23ad-14a7-4a50-ad69-beb1943c62a1.jpeg)
