### ISSUE TITLE
Rebuild EMO System

### ISSUE THREAD

**Issue by narekboghozian** [Triton-AI/evGoKart-electrical-system#16]
## Interconnect Diagram:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/66885970/164091933-9cf0bb68-ecf3-4293-b6e7-5320c87f35c2.png">

(B = Button)

## EMO Switches:
- Drill holes in removable panels
- Insert JST connectors & add strain relief
- Attach to terminals
- Solder cabling to connect to those terminals

## EMO Driver board:
- Make a board to connect switch lines

<img width="470" alt="image" src="https://user-images.githubusercontent.com/66885970/164091986-aa2d3c53-8105-478d-86ce-382af4a5da4e.png">

## JST terminations
- Short out some JST connectors to serve as the end points in the circuit

**Comment by narekboghozian** [comment]
Did some building. Needs to be wired up, @brenner-lim knows what to do.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/66885970/164133202-a7800cee-b38d-419a-b73a-d42af9a8a1df.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/66885970/164133232-7703edac-a74a-401d-bb93-86e5c0ac6f0e.png">

**Comment by brenner-lim** [comment]
Finished the wiring from before and the JST that connects the loop of one side.

<img src="https://user-images.githubusercontent.com/81719924/164339213-3f69d157-3e77-4c4f-afe6-737dd74bdec9.jpg"/>

**Comment by jmsanjua** [comment]
Is the Driver board already made? Also it looks the driver board could just be a splitter of some sort. Does it have to be an actual board?

**Comment by narekboghozian** [comment]
@jmsanjua it's not made, but that's exactly what I was telling @brenner-lim. My only concern with making it as a splitter is that it could be confused with an actual splitter. It's not hard to make it as a small board though.

**Comment by narekboghozian** [comment]
@jmsanjua just make it as a board. Would be dangerous to confuse it with a normal splitter.

**Comment by jmsanjua** [comment]
Do the JST connector's of the driver board need to be male or female?

**Comment by narekboghozian** [comment]
Going away from the board is female since it's 'outputting' from the board.

So the two drawn on top are female. The one on the bottom is male.

**Comment by jmsanjua** [comment]
![1C3A3AB7-2AE7-42B0-8248-7DFD90F11CD1](https://user-images.githubusercontent.com/81659626/164367762-030c2ec2-2333-4db3-a2fd-e4731bfa77b5.jpeg)
This is the driver board I made with the female to the buttons and the male to the relay

**Comment by jmsanjua** [comment]
We can cut it later as we see fit

**Comment by narekboghozian** [comment]
Try not to make things so close like that when you have the space. It risks a short. Short here would mean it never turned off.

**Comment by brenner-lim** [comment]
Finished and tested the EMO system. Now we have to wait for the plate where the cameras will be hooked up and place the final 2 EMOs

The driver board
<img src="https://user-images.githubusercontent.com/81719924/164877740-139995d6-a786-4577-acf0-7609718f8c4d.jpg" alt="drawing" width="200">
