### ISSUE TITLE
Wrap up wiring for DBW (pre-BLDC)

### ISSUE THREAD

**Issue by narekboghozian** [Triton-AI/evGoKart-electrical-system#2]
What's left on PDN-A and PDN-B?

**Comment by brenner-lim** [comment]
From what I can see, PDN-A is missing wiring for the bullet radio. If I recall correctly, the 24V-to-5V DC converter was completed by Juan, but I'm not sure where it is or the exact placement of the radio.

**Comment by bensaxophone** [comment]
Looks like the only thing left on PDN-B for drive-by-wire is to add fuses to the PDB for the 24V power going to the brake and throttle DAC. Other than that, we just need to figure out where to secure everything on the cart. After tomorrow, the WES relay and EMO switches have to be hooked up and secured, upon which the wiring will be done for PDN-B.

For PDN-A, other than what Brenner commented above, we also need to add fuses to all PDB's.

**Comment by narekboghozian** [comment]
Bullet:

DBW doesn't involve bullet, but that will be done with a PoE injector. That was added later so it will be in PDN v0.4. Good catch.


5v converter:

Can be placed anywhere for now since we're assembling the new shelf soon.


LLR (low level radio):

Juan knows the placement for this. It will be on a 45° support for the boom structure.


WES relay:

This hasn't been set up yet, but it will be completed tomorrow. It consists of one of the dual relay modules (two blue relays) and is driven by 5v. Same 5v converter as for the LLR itself. This will cut the 48v signal that is serving as the throttle controller enable.


Fuses:

Yes. The currents can be found using the power profile doc. LMK if you have trouble running that.
